export const journalArticles = [
  {
    slug: 'formentera-by-yacht',
    category: 'Routes',
    categoryEs: 'Rutas',
    title: 'Formentera by yacht: the essential Ibiza day',
    titleEs: 'Formentera en yate: el día imprescindible de Ibiza',
    text: 'Ses Illetes, Espalmador and a sunset return planned by our local team.',
    textEs: 'Ses Illetes, Espalmador y regreso al atardecer, organizado por nuestro equipo local.',
    image: 'https://rentyourboatibiza.com/wp-content/uploads/2025/04/03-6-672x448.jpg',
    date: '12 August 2026',
    dateEs: '12 de agosto de 2026',
    body: [
      'The crossing from Ibiza to Formentera is short, but the feeling of arriving by yacht is completely different. Leave the marina in the morning, watch Ibiza fade behind you and reach the clear, shallow water around Ses Illetes before the busiest part of the day.',
      'A good itinerary is never rushed. We normally suggest time at anchor near Espalmador for swimming and water toys, followed by a relaxed lunch reservation in Formentera. Your captain will adapt the anchorage to the wind and sea conditions so the day remains comfortable.',
      'Fuel, restaurant reservations and water toys should be discussed before departure. Our team provides a clear estimate and confirms what is included with each yacht, avoiding surprises when you return.',
      'The final part is often the most memorable: a slow cruise back toward Ibiza as the light softens over Es Vedrà. Tell us your group size, preferred date and style of yacht, and we will shape the route around you.',
    ],
    bodyEs: [
      'La travesía de Ibiza a Formentera es corta, pero llegar en yate cambia completamente la experiencia. Sal de la marina por la mañana, contempla cómo Ibiza queda atrás y alcanza las aguas claras y poco profundas de Ses Illetes antes de las horas más concurridas.',
      'Un buen itinerario nunca debe tener prisas. Normalmente recomendamos fondear cerca de Espalmador para nadar y disfrutar de los juguetes acuáticos, seguido de una comida tranquila en Formentera. El capitán adaptará el fondeo al viento y al estado del mar.',
      'El combustible, la reserva del restaurante y los juguetes acuáticos deben acordarse antes de salir. Nuestro equipo facilita una estimación clara y confirma todo lo incluido en cada yate para evitar sorpresas al regresar.',
      'El tramo final suele ser el más inolvidable: navegar lentamente de vuelta a Ibiza mientras la luz cae sobre Es Vedrà. Cuéntanos el tamaño del grupo, la fecha y el estilo de yate que prefieres, y diseñaremos la ruta a tu medida.',
    ],
  },
  {
    slug: 'ibiza-yacht-charter-cost',
    category: 'Charter guide',
    categoryEs: 'Guía de alquiler',
    title: 'What does a yacht day in Ibiza really cost?',
    titleEs: '¿Cuánto cuesta realmente un día en yate en Ibiza?',
    text: 'A clear guide to daily rates, fuel, crew and the extras worth choosing.',
    textEs: 'Una guía clara de tarifas, combustible, tripulación y extras que merecen la pena.',
    image: 'https://rentyourboatibiza.com/wp-content/uploads/2025/04/Maiora-99-4-672x448.jpg',
    date: '5 August 2026',
    dateEs: '5 de agosto de 2026',
    body: [
      'A yacht charter price usually starts with the daily boat rate. The size, age, design and season all matter: June and September often offer excellent conditions at a lower rate than July and August.',
      'Always check whether VAT, captain, crew, standard drinks, towels and insurance are included. Fuel is commonly charged separately because the final amount depends on the yacht, speed and chosen route.',
      'Lunch, premium drinks, transfers, extra water toys and marina fees outside the home port are optional additions. We present these separately so you can compare yachts on the same basis.',
      'The best value is not always the lowest headline price. A well-maintained yacht, experienced crew and realistic route make a much greater difference to the day. Share your budget openly and we will recommend the strongest options within it.',
    ],
    bodyEs: [
      'El precio de un alquiler suele comenzar con la tarifa diaria del barco. El tamaño, la antigüedad, el diseño y la temporada influyen: junio y septiembre suelen ofrecer condiciones excelentes con precios inferiores a julio y agosto.',
      'Comprueba siempre si están incluidos el IVA, el capitán, la tripulación, las bebidas estándar, las toallas y el seguro. El combustible suele cobrarse aparte porque depende del yate, la velocidad y la ruta elegida.',
      'La comida, las bebidas premium, los traslados, los juguetes acuáticos adicionales y los amarres fuera del puerto base son extras opcionales. Los presentamos por separado para que puedas comparar todos los yates en igualdad de condiciones.',
      'La mejor opción no siempre es la tarifa inicial más baja. Un yate bien mantenido, una tripulación con experiencia y una ruta realista cambian por completo el día. Comparte tu presupuesto con nosotros y te mostraremos las mejores alternativas.',
    ],
  },
  {
    slug: 'hidden-coves-ibiza',
    category: 'Local secrets',
    categoryEs: 'Secretos locales',
    title: 'Four hidden coves best reached from the sea',
    titleEs: 'Cuatro calas secretas que se disfrutan mejor desde el mar',
    text: 'Quiet anchorages, crystalline water and the right hour to arrive.',
    textEs: 'Fondeos tranquilos, agua cristalina y la mejor hora para llegar.',
    image: 'https://rentyourboatibiza.com/wp-content/uploads/2025/04/02-17-672x448.jpg',
    date: '29 July 2026',
    dateEs: '29 de julio de 2026',
    body: [
      'Ibiza has famous beaches, but a yacht gives you access to smaller corners where the island feels calm again. Cala Llentrisca, Es Portitxol, Cala d’Albarca and the waters beneath the northern cliffs each offer a different perspective.',
      'These are not fixed promises on a map. Wind direction, swell and anchoring restrictions determine which cove is right on a particular day. A local captain chooses the safest and most comfortable option.',
      'Arriving early creates space for a quiet swim, while late afternoon brings softer light and fewer visiting boats. Respect for Posidonia meadows is essential, so every anchorage must use clear sand or an authorised buoy.',
      'Tell us whether you prefer swimming, snorkelling, lunch ashore or complete privacy. We will combine the right coves into a route that works with the conditions rather than against them.',
    ],
    bodyEs: [
      'Ibiza tiene playas famosas, pero un yate permite descubrir pequeños rincones donde la isla recupera su calma. Cala Llentrisca, Es Portitxol, Cala d’Albarca y las aguas bajo los acantilados del norte ofrecen perspectivas muy diferentes.',
      'No son promesas fijas sobre un mapa. La dirección del viento, el oleaje y las restricciones de fondeo determinan qué cala es adecuada cada día. Un capitán local elegirá siempre la opción más segura y cómoda.',
      'Llegar temprano deja espacio para nadar con tranquilidad, mientras que la última hora de la tarde ofrece una luz más suave y menos barcos. Proteger las praderas de Posidonia es esencial: se debe fondear sobre arena clara o utilizar una boya autorizada.',
      'Dinos si prefieres nadar, hacer snorkel, comer en tierra o buscar privacidad total. Combinaremos las calas adecuadas en una ruta que acompañe las condiciones del día.',
    ],
  },
  {
    slug: 'best-month-charter-ibiza',
    category: 'Seasonal guide',
    categoryEs: 'Guía de temporada',
    title: 'The best month to charter in Ibiza',
    titleEs: 'El mejor mes para alquilar un yate en Ibiza',
    text: 'From calm June mornings to warm September sunsets.',
    textEs: 'Desde las mañanas tranquilas de junio hasta los atardeceres cálidos de septiembre.',
    image: 'https://rentyourboatibiza.com/wp-content/uploads/2025/04/5-8-672x448.jpg',
    date: '20 July 2026',
    dateEs: '20 de julio de 2026',
    body: [
      'There is no single best month for everyone. May and early June suit travellers who value quiet anchorages, mild temperatures and strong availability. The sea can feel cooler, but the island is fresh and unhurried.',
      'July and August deliver the warmest water, longest days and fullest Ibiza atmosphere. Demand is highest, so yacht choice, restaurant reservations and departure times should be confirmed well in advance.',
      'September is a local favourite. The water remains warm, the light is beautiful and the pace begins to soften. October can still produce exceptional charter days when the forecast is stable.',
      'Choose the month according to the experience you want, not only the weather. We monitor conditions and availability daily and will be honest when another date or route would create a better day.',
    ],
    bodyEs: [
      'No existe un único mes perfecto para todos. Mayo y principios de junio son ideales para quienes buscan fondeos tranquilos, temperaturas suaves y buena disponibilidad. El agua puede estar más fresca, pero la isla se siente relajada.',
      'Julio y agosto ofrecen el agua más cálida, los días más largos y toda la energía de Ibiza. La demanda es máxima, por lo que conviene confirmar con antelación el yate, los restaurantes y la hora de salida.',
      'Septiembre es uno de los meses favoritos de los locales. El agua sigue cálida, la luz es preciosa y el ritmo empieza a bajar. Octubre todavía puede ofrecer días excepcionales cuando la previsión es estable.',
      'Elige el mes según la experiencia que deseas, no solo por el tiempo. Revisamos diariamente las condiciones y la disponibilidad, y seremos sinceros si otra fecha o ruta puede darte un día mejor.',
    ],
  },
]

export function getJournalArticle(slug) {
  return journalArticles.find((article) => article.slug === slug)
}
